# Generated by Django 2.1.3 on 2018-11-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decaptcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcharecord',
            name='hashkey',
            field=models.CharField(max_length=255, verbose_name='Hashkey'),
        ),
    ]
